export const products = [
  {
    id: "1",
    title: "react tshirt",
    category: "category",
    imageSrc: "https://picsum.photos/seed/picsum6/420/260",
    price: "$23.00",
    rating: 1,
  },
  {
    id: "2",
    title: "chakraUI mug",
    category: "category",
    imageSrc: "https://picsum.photos/seed/picsum5/421/261",
    price: "$15.00",
    rating: 5,
  },
  {
    id: "3",
    title: "black tshirt",
    category: "category",
    imageSrc: "https://picsum.photos/seed/picsum4/422/262",
    price: "$10.25",
    rating: 3.5,
  },
  {
    id: "4",
    title: "react tshirt",
    category: "category",
    imageSrc: "https://picsum.photos/seed/picsum3/420/260",
    price: "$23.00",
    rating: 2.5,
  },
  {
    id: "5",
    title: "chakraUI mug",
    category: "category",
    imageSrc: "https://picsum.photos/seed/picsum2/421/261",
    price: "$15.00",
    rating: 3,
  },
  {
    id: "6",
    title: "black tshirt",
    category: "category",
    imageSrc: "https://picsum.photos/seed/picsum1/422/262",
    price: "$10.25",
    rating: 4.5,
  },
  {
    id: "7",
    title: "react tshirt",
    category: "category",
    imageSrc: "https://picsum.photos/seed/picsum6/420/260",
    price: "$23.00",
    rating: 1,
  },
  {
    id: "8",
    title: "chakraUI mug",
    category: "category",
    imageSrc: "https://picsum.photos/seed/picsum5/421/261",
    price: "$15.00",
    rating: 5,
  },
  {
    id: "9",
    title: "black tshirt",
    category: "category",
    imageSrc: "https://picsum.photos/seed/picsum4/422/262",
    price: "$10.25",
    rating: 3.5,
  },
  {
    id: "10",
    title: "react tshirt",
    category: "category",
    imageSrc: "https://picsum.photos/seed/picsum2/421/261",

    price: "$23.00",
    rating: 2.5,
  },
  {
    id: "11",
    title: "chakraUI mug",
    category: "category",
    imageSrc: "https://picsum.photos/seed/picsum3/420/260",
    price: "$15.00",
    rating: 3,
  },
  {
    id: "12",
    title: "black tshirt",
    category: "category",
    imageSrc: "https://picsum.photos/seed/picsum1/422/262",
    price: "$10.25",
    rating: 1.5,
  },
];
